/**
 * This file was generated by the Jeddict
 */
package com.gbs.compliance.susep.model;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author Stibiun
 */
@Entity
public class ComplianceEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Basic
    private String eventType;
    @Basic
    private String complianceStatus;
    @Basic
    private String description;
    @ManyToOne(targetEntity = SusepEvent.class)
    private SusepEvent susepEvent;
    @ManyToOne(targetEntity = User.class)
    private User user;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEventType() {
        return this.eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getComplianceStatus() {
        return this.complianceStatus;
    }

    public void setComplianceStatus(String complianceStatus) {
        this.complianceStatus = complianceStatus;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public SusepEvent getSusepEvent() {
        return this.susepEvent;
    }

    public void setSusepEvent(SusepEvent susepEvent) {
        this.susepEvent = susepEvent;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}