/**
 * This file was generated by the Jeddict
 */
package com.gbs.compliance.susep.model;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.ws.rs.FormParam;

/**
 * @author Stibiun
 */
@Entity
public class ComplianceEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("id")
    private Long id;
    @Basic
    @FormParam("eventType")
    private String eventType;
    @Basic
    @FormParam("status")
    private String status;
    @ManyToOne(targetEntity = SusepEvent.class)
    private SusepEvent susepEvent;
    @ManyToOne(targetEntity = User.class)
    private User user;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEventType() {
        return this.eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public SusepEvent getSusepEvent() {
        return this.susepEvent;
    }

    public void setSusepEvent(SusepEvent susepEvent) {
        this.susepEvent = susepEvent;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}