/**
 * This file was generated by the Jeddict
 */
package com.gbs.compliance.susep.model;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.ws.rs.FormParam;

/**
 * @author Stibiun
 */
@Entity
public class SusepEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("id")
    private Long id;
    @Basic
    @FormParam("name")
    private String name;
    @Basic
    @FormParam("creationDate")
    private String creationDate;
    @Basic
    @FormParam("description")
    private String description;
    @Basic
    @FormParam("url")
    private String url;
    @Basic
    @FormParam("status")
    private String status;
    @ManyToOne(targetEntity = SusepEventStatus.class)
    private SusepEventStatus susepEventStatus;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public SusepEventStatus getSusepEventStatus() {
        return this.susepEventStatus;
    }

    public void setSusepEventStatus(SusepEventStatus susepEventStatus) {
        this.susepEventStatus = susepEventStatus;
    }
}